sudo: required
services:
  - docker


before_install:
  - docker build -t rafeeqce/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rafeeqce/docker-react npm test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-549138032787"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  
